enable-email-notifications: true
on:
  workflow_dispatch:
  push:
#  schedule:
#    - cron: '17 05 * * 1'
#      timezone: "America/New_York"
jobs:
  container:
    runs-on: codeberg-medium

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install buildah
        run: |
          echo Repository name: ${{ env.FORGEJO_REPOSITORY }}
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends buildah

      - name: Build OCI image
        env:
          STORAGE_DRIVER: vfs
          BUILDAH_ISOLATION: chroot
        run: |
          CONT_LATEST="codeberg.org/${{ env.FORGEJO_REPOSITORY }}:latest"
          buildah --storage-driver="$STORAGE_DRIVER" \
            bud --isolation="$BUILDAH_ISOLATION" \
            --build-arg-file=argfile.conf \
            -t "$CONT_LATEST" .
          buildah --storage-driver $STORAGE_DRIVER from --pull=never --name version "$CONT_LATEST"
          CONT_VER=$(buildah --storage-driver $STORAGE_DRIVER run version sh -c "nginx -V 2>&1 | grep -oP '(?<=nginx version: nginx/)(.+)$'")
          CONT_VER=${CONT_VER//[+~]/_}
          echo "Container version: ${CONT_VER}"
          CONT_WITH_VER=${CONT_LATEST%%:*}:${CONT_VER}
          buildah --storage-driver $STORAGE_DRIVER tag "$CONT_LATEST" "${CONT_WITH_VER}"
          echo ${{ secrets.PACKAGE_RW }} | buildah login --password-stdin -u ${{ env.FORGEJO_ACTOR }} codeberg.org
          buildah --storage-driver $STORAGE_DRIVER push "${CONT_LATEST}"
          buildah --storage-driver $STORAGE_DRIVER push "${CONT_WITH_VER}"
